app/recipes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Length
from wtforms.widgets import TextArea


class SearchForm(FlaskForm):
    search_user_text = StringField('Searching for anybody in particular?',
                                   validators=[DataRequired(), Length(min=0, max=40)])
    search_country_text = StringField('Which country are you interested in?',
                                      validators=[DataRequired(), Length(min=0, max=40)])
    submit = SubmitField('Submit')

class RecipePostForm(FlaskForm):
    recipe = StringField('Recipe title',
                         validators=[DataRequired(), Length(min=0, max=32)],
                         widget=TextArea())
    ingredients = StringField('Recipe ingredients',
                              validators=[DataRequired(), Length(min=0, max=1024)],
                              widget=TextArea())
    steps = StringField('Recipe steps',
                        validators=[DataRequired(), Length(min=0, max=4096)],
                        widget=TextArea())
    post_id = StringField('Post ID', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/recipes/__init__.py
from flask import Blueprint

bp = Blueprint('recipes', __name__)

from app.recipes import routes

app/recipes/routes.py
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_required
from app.recipes.forms import RecipePostForm, SearchForm
from app.models import User, Country, Post
from app.recipes import bp
import os


@bp.route('/country/<country_name>', methods=['GET', 'POST'])
@login_required
def country(country_name):
    country = Country.get_country_by_name(country_name).first()
    if country is None:
        flash('Country {} not found.'.format(country_name))
        return redirect(url_for('main.index'))

    form = SearchForm()
    already_picked = Post.user_has_post_in_country(current_user.id, country.id)

    if request.method == 'POST':
        button_clicked = request.form.get('submit button')

        if button_clicked == 'select country':
            if not already_picked:
                Post.create_empty_post(country.id)
            return redirect(url_for('recipes.available_posts', country_name='all'))

        if button_clicked == 'search user':
            searched_user = User.get_user_by_username(form.search_user_text.data).first()
            if not searched_user is None:
                return redirect(url_for('recipes.user_country', username=searched_user.username,
                                        country_name=country_name))
            flash('User {} not found'.format(form.search_user_text.data))

        if button_clicked == 'search country':
            searched_country = Country.get_country_by_name(form.search_country_text.data).first()
            if not searched_country is None:
                return redirect(url_for('recipes.country',country_name=searched_country.name))
            flash('Country {} not found'.format(form.search_country_text.data))

    page = request.args.get('page', 1, type=int)
    posts = Post.get_others_posts_by_country_id(country.id).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('recipes.country_by_user', country_name=country_name, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('recipes.country_by_user', country_name=country_name, page=posts.prev_num) \
        if posts.has_prev else None

    return render_template('recipes/country.html', title='{}'.format(country_name),
                           country=country, form=form, already_picked=already_picked,
                           posts=posts.items, next_url=next_url, prev_url=prev_url)

@bp.route('/available_posts/<country_name>', methods=['GET', 'POST'])
@login_required
def available_posts(country_name):
    search_form = SearchForm()
    form = RecipePostForm()

    page = request.args.get('page', 1, type=int)
    if country_name == 'all':
        available_posts = Post.get_my_available_posts().paginate(
            page, current_app.config['POSTS_PER_PAGE'], False)
        general = True
    else:
        country = Country.get_country_by_name(country_name).first()
        if country is None:
            flash('Country {} not found'.format(country_name))
            return redirect(url_for('main.index'))
        available_posts = Post.get_my_available_posts_by_country_id(country.id).paginate(
            page, current_app.config['POSTS_PER_PAGE'], False)
        general = False

    next_url = url_for('recipes.available_posts', country_name=country_name,
                       page=available_posts.next_num) if available_posts.has_next else None
    prev_url = url_for('recipes.available_posts', country_name=country_name,
                       page=available_posts.prev_num) if available_posts.has_prev else None

    if request.method == 'POST' and request.form.get('submit button') == 'search country':
        searched_country = Country.get_country_by_name(search_form.search_country_text.data).first()
        if not searched_country is None:
            return redirect(url_for('recipes.available_posts', country_name=searched_country.name))
        flash('Country {} not found'.format(search_form.search_country_text.data))

    if form.validate_on_submit():
        post = Post.get_post_by_id(form.post_id.data).first()
        if post is None:
            flash('An unhandled error pop up')
            return redirect(url_for('main.index'))
        post.submit(recipe=form.recipe.data, ingredients=form.ingredients.data,
                    steps=form.steps.data)
        flash('Your post is now alive!')
        
        return redirect(url_for('recipes.my_posts', country_name='all'))

    return render_template('recipes/my_posts.html', title='Available posts',
                           form=form, search_form=search_form, posts=available_posts.items,
                           country_name=country_name.capitalize(),
                           has_data=False, general=general,
                           next_url=next_url, prev_url=prev_url)

@bp.route('/my_posts/<country_name>', methods=['GET', 'POST'])
@login_required
def my_posts(country_name):
    search_form = SearchForm()
    form = RecipePostForm()

    page = request.args.get('page', 1, type=int)
    if country_name == 'all':
        posts = Post.get_posts_by_user_id(current_user.id).paginate(
            page, current_app.config['POSTS_PER_PAGE'], False)
        general = True
    else:
        country = Country.get_country_by_name(country_name).first()
        posts = Post.get_posts_by_user_and_country_ids(current_user.id, country.id).paginate(
            page, current_app.config['POSTS_PER_PAGE'], False)
        general = False
    next_url = url_for('recipes.my_posts', country_name=country_name, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('recipes.my_posts', country_name=country_name, page=posts.prev_num) \
        if posts.has_prev else None

    if request.method == 'POST' and request.form.get('submit button') == 'search country':
        searched_country = Country.get_country_by_name(search_form.search_country_text.data).first()
        if not searched_country is None:
            return redirect(url_for('recipes.my_posts', country_name=searched_country.name))
        flash('Country {} not found'.format(search_form.search_country_text.data))

    if form.validate_on_submit():
        post = Post.get_post_by_id(form.post_id.data).first()
        if post is None:
            flash('An error!')
        if not post.edit(form.recipe.data, form.ingredients.data, form.steps.data):
            flash('No changes were made. Nothing to update')
        else:
            flash('Your post was updated')
            return redirect(url_for('recipes.my_posts', country_name='all'))

    return render_template('recipes/my_posts.html', title='My creations', form=form,
                           user=current_user, search_form=search_form,
                           posts=posts.items, has_data=True, general=general,
                           next_url=next_url, prev_url=prev_url)

@bp.route('/user/<username>/country/<country_name>', methods=['GET', 'POST'])
@login_required
def user_country(username, country_name):
    form = SearchForm()

    country = Country.get_country_by_name(country_name).first()
    if country is None:
        flash('Country {} not found.'.format(country_name))
        return redirect(url_for('main.index'))

    user = User.get_user_by_username(username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('main.index'))

    if request.method == 'POST':
        button_clicked = request.form.get('submit button')

        if button_clicked == 'search user': 
            searched_user = User.get_user_by_username(form.search_user_text.data).first()
            if not searched_user is None:
                return redirect(url_for('main.user', username=searched_user.username))
            flash('User {} not found'.format(form.search_user_text.data))

        if button_clicked == 'search country':
            searched_country = Country.get_country_by_name(form.search_country_text.data).first()
            if not searched_country is None:
                 return redirect(url_for('recipes.country',country_name=searched_country.name))
            flash('Country {} not found'.format(form.search_country_text.data))
                
    page = request.args.get('page', 1, type=int)
    posts = Post.get_posts_by_user_and_country_ids(user.id, country.id).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('recipes.user_country', username=username, country_name=country_name,
                       page=posts.next_num) if posts.has_next else None
    prev_url = url_for('recipes.user_country', username=username, country_name=country_name,
                       page=posts.prev_num) if posts.has_prev else None

    return render_template('recipes/country.html', title='{}'.format(country_name), 
                            user=user, country=country, form=form, 
                            posts=posts.items, next_url=next_url, prev_url=prev_url)

@bp.route('/uploads/post/<post_id>', methods=['GET', 'POST'])
def upload(post_id):
    post = Post.get_post_by_id(post_id).first()
    if post is None:
        flash('Post {} not found.'.format(post.id))
        return redirect(url_for('main.index'))
    
    if request.method == 'POST':
        allowed_extentions = ['jpeg', 'jpg', 'png']
        path = os.getcwd() + '/app/static/' + post.image_url
        f = request.files.get('file')
        filename = f.filename
        if filename.split('.')[1] in allowed_extentions:
            if os.path.isfile(path):
                os.remove(path)
                post.create_image_url()
                path = os.getcwd() + '/app/static/' + post.image_url
            f.save(path)

app/templates/recipes/country.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{country.name}}</h1>
    <hr>
    <div class="row text-center">
        <div class='col-md-3'>
            <img class="panel panel-default"
            src="{{ url_for('static', filename='flags/'+country.flag_url) }}"
            alt="{{ country.name }}'s flag" width="125" height="80">
        </div>
        <div class='col-md-3'>
            Did you know? <br>
            {{ country.name }}'s capital city is:
            {{ country.capital }}<br>
            <form action="" method="post">
            {{ form.hidden_tag() }}
            <p>
            {% if already_picked %}
                <input type="hidden" name="submit button",
                value="select country">
                {{ form.submit(value='Try now!',
                class_='btn btn-default') }}
            {% else %}
                <input type="hidden" name="submit button",
                value="select country">
                {{ form.submit(value='Give it a shot?',
                class_='btn btn-default') }}
            {% endif %}
            </p>
            </form>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-3">
            <form action="" method="post">
                {{ form.hidden_tag() }}
                {{ form.search_user_text.label }} <br>
                {{ form.search_user_text(cols="20", rows="1", class_='btn btn-default') }}
                <input type="hidden" name="submit button", value="search user">
                {{ form.submit(value="Search user", class_='btn btn-default') }}
            </form>
        </div>
        <div class="col-md-3">
            <form action="" method="post">
                {{ form.hidden_tag() }}
                {{ form.search_country_text.label }} <br>
                {{ form.search_country_text(cols="20", rows="1", class_='btn btn-default') }}
                <input type="hidden" name="submit button", value="search country">
                {{ form.submit(value="Search country", class_='btn btn-default') }}
            </form>
        </div>
    </div>
    <hr>
    {% if posts %}
        {% if user %}
            <h2>Look what {{ user.username }} has made:</h2>
        {% else %}
            <h2>Look what other users have made:</h2>
        {% endif %}
        {% for post in posts %}
            {% include '_post.html' %}
        {% endfor %}
    {% else %}
        <center>
        {% if user %}
            <h2>It seems {{ user.username }} has not posted a recipe from {{ country.name }}</h2>
        {% else %}
            <h2>It seems nobody has posted a recipe from {{ country.name }}. Be the first one!</h2>
        {% endif %}
        </center>
    {% endif %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Newer posts
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older posts <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/recipes/my_posts.html
{% extends "base.html" %}

{% block app_content %}
    {% if has_data %}
        <h1>Take a look at your creations:</h1>
    {% else %}
        <h1>Available posts:</h1>
    {% endif %}

    {% if search_form %}
    <form action="" method="post">
        {{ search_form.hidden_tag() }}
        {{ search_form.search_country_text.label }} <br>
        {{ search_form.search_country_text(cols="20", rows="1", class_='btn btn-default') }}
        <input type="hidden" name="submit button", value="search country">
        {{ search_form.submit(value="Search country", class_='btn btn-default') }}
    </form>
    {% endif %}
    <hr>
    {% if posts %}
    {% for post in posts %}
    <div class="row  text-center">
        <div class="col-md-3">
            <p><img class="panel panel-default"
                src="{{ url_for('static', filename='flags/'+post.origin.flag_url) }}"
                alt="{{ post.origin.name }}'s flag" width="125" height="80">
            </p>
            <p>{{ post.origin.name }}</p>
        </div>
        <div class="col-md-3">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            {% set f = form.recipe.process_data(post.recipe) %}
            {% set f = form.ingredients.process_data(post.ingredients) %}
            {% set f = form.steps.process_data(post.steps) %}
            {% set f = form.post_id.process_data(post.id) %}
            <p>
                What did you cook?<br>
                {{ form.recipe(rows="1",
                class_='btn btn-default') }}<br>
            </p>
            <p>
                What did you use?<br>
                {{ form.ingredients(rows="2",
                class_='btn btn-default') }}<br>
            </p>
            <p>
                How did you make it?!<br>
                {{ form.steps(rows="3",
                class_='btn btn-default') }}<br>
            </p>
            <style>
                .hidden{
                    visibility: hidden;
                }
            </style>
            <p class="hidden">
                {{ form.post_id() }}
            </p>
            <input type="hidden" name="submit button", value="submit recipe">
            <p>{{ form.submit(class_='btn btn-default') }}</p>
        </form>
        </div>
        {% if post.has_image %}
        <div class="col-md-3">
            <img class="panel panel-default"
            src="{{ url_for('static', filename=post.image_url) }}"
            alt="{{ url_for('static', filename=post.image_url) }}"
            width="125" height="125">
        </div>
        {% endif %}
        {{ dropzone.load_css() }}
        {{ dropzone.style('border: 2px dashed #0087F7; margin: 10%; min-height: 40px;') }}
        <div class="col-md-3">
            {{ dropzone.load_js() }}
            {{ dropzone.create(action = url_for('recipes.upload', post_id=post.id)) }}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <center>
        {% if general %}
            {% if has_data %}
                <h2>It seems you haven't add any recipe yet</h2>
            {% else %}
                <h2>It seems you don't have any available recipe</h2>
            {% endif %}
        {% else %}
            {% if has_data %}
                <h2>It seems you haven't cooked anything from {{ country_name }}</h2>
            {% else %}
                <h2>It seems you don't have any available recipe for {{ country_name }}</h2>
            {% endif %}
        {% endif %}
    </center>
    {% endif %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Newer posts
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older posts <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}